### ISSUE TITLE
Python 3 iteration and bytes with Gstreamer decoder

### ISSUE THREAD

**Issue by xix-xeaon** [sampsyo/audioread#25]
The iterator for the Gstreamer decoder in Python 3 gives this error:
```
Traceback (most recent call last):
  File "./undermystic.py", line 23, in <module>
    for buf in f:
TypeError: iter() returned non-iterator of type 'GstAudioFile'
```

And also, the ```_new_sample``` function turns the byte-data into utf-8 strings.

I've fixed these simple Python 3 issues and will do a pull request.

**Comment by sampsyo** [comment]
Fixed in #26.
